### ISSUE TITLE
NoSuchFieldException on Java 10

### ISSUE THREAD

**Issue by YashchenkoN** [flapdoodle-oss/de.flapdoodle.embed.mongo#243]
I found that #241 is resolved now. I use the latest version:

 ```
 <dependency>
     <groupId>de.flapdoodle.embed</groupId>
     <artifactId>de.flapdoodle.embed.mongo</artifactId>
     <version>2.0.3</version>
     <scope>test</scope>
 </dependency>
```
but still see the issue on MacOS:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
```

**Comment by Loki-Afro** [comment]
@YashchenkoN well it is resolved but looking further down the comments you would find https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/78 ;)

**Comment by getalphacode** [comment]
Getting the same issue with 2.0.3 with java 10

**Comment by rshmiraf** [comment]
For me using 2.0.2 instead of 2.0.3 doesn't change anything. Still the same error.

**Comment by fluidsonic** [comment]
Same error here on macOS. Version 3.0.0.

`ProcessImpl` clearly doesn't have a field `handle`.

However there are private field `processHandle` and a function `toHandle()`:
![image](https://user-images.githubusercontent.com/85242/128647126-62d4b8c8-6782-4fa4-bf5f-a6bfb54a6ce1.png)
