### ISSUE TITLE
 unrecognised option '--noprealloc' with Spring Boot 2.6.2 and de.flapdoodle.embed.mongo 3.2.7

### ISSUE THREAD

**Issue by milanjour** [flapdoodle-oss/de.flapdoodle.embed.mongo#367]
Hi, I am upgrading from Spring Boot 2.5.8 to 2.6.2.
Since now the property `spring.mongodb.embedded.version` is mandatory, I am annotating my test (in a Maven multi-module project) with:
```
@DataMongoTest(properties = {
    "spring.mongodb.embedded.version=5.0.1"
})
```
but I have a 
`Caused by: java.lang.RuntimeException: Could not start process: <EOF>`

I debugged it, and seen that Mongo is started with this command:
```
/var/folders/rg/1n7z661961s444dbs1cw3s380000gq/T/extract-1d38d22e-0012-4abf-ba43-3e872d888de9extractmongod --dbpath /var/folders/rg/1n7z661961s444dbs1cw3s380000gq/T/embedmongo-db-a8b668e5-4944-4198-84e6-75067c3fa79a --noauth --noprealloc --smallfiles --nojournal --nohttpinterface --port 60078 --bind_ip 127.0.0.1
```
which, when manually started, fails with the following errors:
```Error parsing command line: unrecognised option '--noprealloc'```
```Error parsing command line: unrecognised option '--smallfiles'```
```Error parsing command line: unrecognised option '--nohttpinterface'```

I am currently running it on a x86 Mac, but this should run on all environments.
Is there any Spring Configuration property to set these?

**Comment by michaelmosmann** [comment]
Hmm.. i have to investigate this..

**Comment by michaelmosmann** [comment]
@milanjour can you try 5.0.2 instead?

**Comment by xiaodongli7** [comment]
same issue for 4.4.8.
old embed db 3.5.5 is good.
waiting for fix, thanks

**Comment by michaelmosmann** [comment]
@xiaodongli7 hmm.. did a new release.. 5.0.5. should work now, but i suspect that the way spring integrates embed mongo is responsible for these issues..

**Comment by xiaodongli7** [comment]
still not working in 4.4.8. yes, it is working for 5.0.5. Thank you

**Comment by michaelmosmann** [comment]
@xiaodongli7 maybe 4.4.9 may work too.. i think it depends if a version is in this list: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java

**Comment by xiaodongli7** [comment]
> @xiaodongli7 maybe 4.4.9 may work too.. i think it depends if a version is in this list: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java

yes, it works. Thank you michael

**Comment by michaelmosmann** [comment]
@xiaodongli7 thanks for testing:)

**Comment by GuillaumeMartial** [comment]
Same problem on Linux...

**Comment by michaelmosmann** [comment]
@GuillaumeMartial which linux version do you use? any error message?
